const CACHE='bozo-uni-v5';
const refreshVersion=s=>(s.match(/const APP_VERSION\s*=\s*['"](\d{4}-\d{2}-\d{2}\.\d+)['"]/)||[])[1];
const refreshNewer=(a,b)=>{const[x,n]=a.split('.'),[y,m]=b.split('.');return x>y||(x===y&&+n>=+m)};
const refreshHit=async(c,v)=>{for(const key of[self.registration.scope,new URL('index.html',self.registration.scope).href]){const hit=await c.match(key);if(hit?.ok&&refreshVersion(await hit.clone().text())===v)return hit}};
self.addEventListener('message',e=>{if(e.data?.type!=='bp-refresh'||!e.ports?.[0])return;const port=e.ports[0];e.waitUntil((async()=>{let timer;try{const scope=self.registration.scope;if(!e.source?.url?.startsWith(scope)||!/^\d{4}-\d{2}-\d{2}\.\d+$/.test(e.data.v))throw Error('wrong scope');const abort=new AbortController();timer=setTimeout(()=>abort.abort(),10000);const vr=await fetch(new Request(new URL('version.json?t='+Date.now(),scope),{cache:'no-store',signal:abort.signal}));if(!vr.ok)throw Error('version');const v=(await vr.json()).v;if(!/^\d{4}-\d{2}-\d{2}\.\d+$/.test(v))throw Error('version');if(!refreshNewer(v,e.data.v)){port.postMessage({ok:false,reason:'rollback'});return}const c=await caches.open(CACHE);if(v===e.data.v&&await refreshHit(c,v)){port.postMessage({ok:true,v});return}const page=await fetch(new Request(new URL('index.html?bp-prepare='+Date.now(),scope),{cache:'reload',signal:abort.signal}));if(!page.ok||refreshVersion(await page.clone().text())!==v)throw Error('page not ready');await c.put(new URL('__refresh__',scope).href,page.clone());await c.put(scope,page.clone());await c.put(new URL('index.html',scope).href,page);port.postMessage({ok:true,v})}catch(x){port.postMessage({ok:false})}finally{clearTimeout(timer)}})())});
const ASSETS=['./','./index.html','./manifest.json','./icon.svg'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS.map(a=>new Request(a,{cache:'reload'})))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('bozo-uni-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const url=new URL(e.request.url);
  if(url.origin!==location.origin)return;
  if(e.request.mode==='navigate'&&url.searchParams.has('bp-refresh')){e.respondWith((async()=>{const c=await caches.open(CACHE),hit=await c.match(new URL('__refresh__',self.registration.scope).href);if(hit&&refreshVersion(await hit.clone().text())===url.searchParams.get('bp-refresh')){await c.delete(new URL('__refresh__',self.registration.scope).href).catch(()=>{});return hit}const cached=await refreshHit(c,url.searchParams.get('bp-refresh'));if(cached)return cached;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),10000);try{return await fetch(new Request(e.request,{cache:'reload',signal:abort.signal}))}catch(x){return(await c.match(url.origin+url.pathname))||(await c.match(self.registration.scope))||Response.error()}finally{clearTimeout(timer)}})());return}
  // network first, always revalidated against the server, cache only as the offline fallback
  const net=fetch(new Request(e.request,{cache:'no-cache'})).then(r=>{if(r.ok&&(!url.search||e.request.mode==='navigate')){const cp=r.clone();caches.open(CACHE).then(c=>c.put(url.search?url.origin+url.pathname:e.request,cp))}return r});   // opening from a notification link keeps the offline copy up to date, one entry per address: one-off links (?t=) used to pile up forever
  if(e.request.mode!=='navigate'){e.respondWith(url.search?net:net.catch(()=>caches.match(e.request,{ignoreSearch:true})));return}
  // weak signal: after 3 s open the copy already on the phone instead of sitting on a blank screen (the app still checks for a newer build once it is up)
  e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(hit=>hit?Promise.race([net.catch(()=>null),new Promise(r=>setTimeout(()=>r(null),3000))]).then(r=>r||hit):net));
});
// phone notifications: always show one (iPhones drop subscriptions that stay silent); a tap opens the app
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(x){d={body:e.data?e.data.text():''}}
  e.waitUntil(self.registration.showNotification(d.title||'Bozo Parlay',{body:d.body||'',tag:d.tag||undefined,renotify:!!d.tag,icon:new URL('icon-192.png',self.registration.scope).href,data:{url:d.url||self.registration.scope}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const url=(e.notification.data&&e.notification.data.url)||self.registration.scope;
  e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs){if(c.url.startsWith(self.registration.scope)&&'focus'in c){c.postMessage({type:'bp-open',url});return c.focus()}}return self.clients.openWindow(url)}))});
